baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo Learn Documentation"
theme = "hugo-pathways-theme"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

publishURL = "http://digital-storytelling.lsupathways.org"

[params]
  editURL = "https://digital-storytelling.lsupathways.org/admin"
  description = "Educational material for Digital Storytelling"
  author = "Tate Carson"
  showVisitedLinks = true
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Educational material for Pre-Engineering"
weight = 1
languageName = "English"




